resources:
  repositories:
  - repository: Shared_Templates
    type: github
    endpoint: karty333
    name: karty333/Shared_Templates
pool:
  vmImage: ubuntu-latest
stages:
 - stage: Install
   jobs: 
    - job: npminstall
      steps:
       - checkout: self
       - checkout: Shared_Templates
- template: MavenTemplate.yml@Shared_Templates
- template: ArtifactoryTemplate.yml@Shared_Templates
- template: ArtifactoryDownload.yml@Shared_Templates
 
