resources:
  repositories:
  - repository: Shared_Templates
    type: github
    endpoint: karty333
    name: karty333/Shared_Templates
pool:
  vmImage: ubuntu-latest
stages:
  - template: project/MavenTemplate.yml
  - template: project/target/ArtifactoryTemplate.yml
  - template: project/target/ArtifactoryDownload.yml
 
