resources:
  repositories:
  - repository: Shared_Templates
    type: github
    endpoint: karty333
    name: karty333/Shared_Templates
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
  - checkout: Shared_Templates
  - script: |
        echo "hello to my first Build"
        ls -la Shared_Templates
  - template: ../Shared_Templates/MavenTemplate.yml
  - template: ../Shared_Templates/ArtifactoryTemplate.yml
  - template: ../Shared_Templates/ArtifactoryDownload.yml
 
