resources:
  repositories:
  - repository: Shared_Templates
    type: github
    endpoint: karty333
    name: karty333/Shared_Templates
pool:
  vmImage: ubuntu-latest
stages:
  - template: Shared_Templates/MavenTemplate.yml
  - template: Shared_Templates/ArtifactoryTemplate.yml
  - template: Shared_Templates/ArtifactoryDownload.yml
 
